---
title: "Agricultural Niches"
output: html_notebook
---

```{r}
library(raster)
library(rasterVis)
library(tidyverse)
library(mgcv)
```


```{r}
wheat.area <- raster('~/Downloads/Ramankutty Crops/wheat_HarvAreaYield2000_Geotiff/wheat_HarvAreaYield2000_Geotiff/wheat_HarvestedAreaFraction.tif')
```

```{r}
levelplot(wheat.area)
```

```{r}
temp <- brick('Data/CHELSA/temp.nc')
```

```{r}
gdd_interp <- function(x){
    if(any(is.na(x))){return(NA)} else{
    daily <- gam(x ~ s(doy, bs = 'cc', k = 12), knots = list(doy = c(1, 366))) %>%
        predict.gam(data.frame(doy = 1:365)) 
    daily[daily < 5] <- 5
    daily[daily > 30] <- 30
    return(sum(daily - 5))
    }
}

doy <-c(15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349)

beginCluster(4)
test <- clusterR(temp, calc, args = list(fun = gdd_interp), export = 'doy')
endCluster()

writeRaster(gdd, 'gdd_global.tif')
```

```{r}
plot(gdd, wheat.area, maxpixels = 1000000)
```


```{r}
alpha <- raster('~/Downloads/CGIAR PET/ALPHA/alpha/w001001.adf') %>% resample(gdd)

bbox <- extent(-10, 20, 28, 38)

prec <- brick('Data/CHELSA/prec.nc') %>% crop(bbox)
tmax <- brick('Data/CHELSA/tmax.nc') %>% crop(bbox)
tmin <- brick('Data/CHELSA/tmin.nc') %>% crop(bbox)

srad <- list.files('~/Downloads/CGIAR PET/ET_SolRad', full.names = T) %>%
  stack %>%
  crop(bbox) %>%
  resample(prec) %>%
  .[[c(1,5:12, 2:4)]] %>%
  `*`(2.45) #convert to mj/m2/day

library(SPEI)

pet <- hargreaves(tmin %>% getValues %>% t, 
                  tmax %>% getValues %>% t, 
                  Ra = srad %>% getValues %>% t, 
                  Pre = prec %>% getValues %>% t, na.rm = T) %>%
  t %>%
  setValues(tmin, .)

levelplot(pet)
levelplot(sum(prec)/sum(pet))


swc <- setValues(pet[[1]], 100) %>% mask(pet[[1]])
aet1 <- setValues(pet[[1]], 0) %>% mask(pet[[1]])
for(i in 1:12){
  ksoil <- swc / 350
  aet <- pet[[i]] * ksoil
  aet1 <- aet1 + aet
  swc.tmp <- swc + prec[[i]] * (1 - .15) - aet
  swc <- reclassify(swc.tmp, c(-Inf, 0, 0, 350, Inf, 350))
}
alpha2 <- aet1/sum(pet)



levelplot(alpha)

wheat <- crop(wheat.area, bbox)
plot(alpha, wheat)
levelplot(swc)
levelplot(wheat)

plot(alpha)
plot(alpha, wheat, maxpixels = 1000000)

```

```{r}

beginCluster(2)
ph.sg <- raster('~/Downloads/SoilGrids250/PHIHOX_M_sl4_250m_ll.tif') %>%
  resample(gdd) %>%
  `*`(.1)
c.sg <- raster('~/Downloads/SoilGrids250/OCSTHA_M_30cm_250m_ll.tif') %>%
  resample(gdd) %>%
  `*`(.1)
endCluster()


plot(ph.sg)
plot(c.sg)

plot(ph.sg, wheat.area,  maxpixels = 1000000)
plot(c.sg, wheat.area,  maxpixels = 1000000)
```

```{r}
dat <- brick(c(wheat.area, alpha, gdd, ph.sg, c.sg)) %>% 
  as.data.frame(na.rm = T, xy = T) %>%
  rename(wheat_area = wheat_HarvestedAreaFraction, alpha = w001001, gdd = layer, ph = PHIHOX_M_sl4_250m_ll, c = OCSTHA_M_30cm_250m_ll)

dat %>%
  mutate(alpha_int = as.integer(alpha)) %>%
ggplot(aes(alpha_int, wheat_area, group = alpha_int)) +
  geom_boxplot(notch=FALSE, outlier.shape=NA, fill="red", alpha=0.2)

dat %>%
  mutate(alpha_int = as.integer(alpha)) %>%
  group_by(alpha_int) %>%
  summarise(avg = mean(wheat_area)) %>%
ggplot(aes(alpha_int, avg)) +
  geom_point()


test <- gam(wheat_area ~ s(gdd, bs = ) + s(alpha) + s(ph) + s(c) + s(x,y, bs = 'sos'), family = betar(link = 'logit'), data = dat)
```

