---
title: "Downscaling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(raster)
library(rasterVis)
library(tidyverse)
library(mgcv)
library(fields)
library(parallel)
```


## Downscaling

Interpolate climate data using splines.
```{r warnings = F}
tpsInterp <- function(rast.brick){
  target <- resample(rast.brick[[1]], prec.obs[[1]])
  
  lapply(1:nlayers(rast.brick), function(rast.index){
    rast.map <- rast.brick[[rast.index]]
    xy <- data.frame(xyFromCell(rast.map, 1:ncell(rast.map)))
    v <- getValues(rast.map)
    tps <- Tps(xy, v)
    interpolate(target, tps)
  }) %>% unlist %>% brick
}

```

```{r}
bbox <- extent(-10, 20, 28, 38)

elev1k <- raster('~/gdrive/Data/SRTM_1km.tif') %>% crop(bbox)

na.mask <- elev1k %>% aggregate(fact = 5) %>% clump %>% mask(., ., maskvalue = 7, inverse = T) %>% aggregate(fact = 2)
```

```{r}
prec.obs <- brick('Data/CHELSA/prec.nc') %>% crop(bbox) %>% mask(na.mask)
elev <- resample(elev1k, prec.obs) %>% mask(na.mask)
dco <- elev %>%
  reclassify(c(-Inf, Inf, NA, NA, NA, 1)) %>% # reverse NA and non-NA cells
  distance(doEdge = T) %>% # calculate the distances
  mask(elev) %>% # mask out ocean cells  
  `/`(1000) # convert to km
aspect <- elev  %>% terrain(opt='aspect', unit = 'degrees') %>% projectRaster(crs = "+proj=lcc")

slope <- elev1k %>%
  terrain(opt = 'slope', unit = 'degrees') %>% 
  aggregate(fact = 10, fun = median) %>% 
  mask(na.mask) %>% 
  projectRaster(crs = "+proj=lcc") 

levelplot(brick(aspect,aspect1))

rough <- terrain(elev, opt = 'roughness')

trefht <- brick()

u <- brick('~/Downloads/b40.lm1850-2005.1deg.002.cam2.h0.U.185001-200512.nc', level = 23) %>%
  .[[1212:1871]] %>%
  rotate %>%
  crop(bbox, snap = 'out') %>%
  tpsInterp %>%
  stackApply(1:12, mean) %>%
  crop(bbox) %>%
  mask(na.mask)

v <- brick('~/Downloads/b40.lm1850-2005.1deg.002.cam2.h0.V.185001-200512.nc', level = 23) %>%
  .[[1212:1871]] %>%
  rotate %>%
  crop(bbox) %>%
  tpsInterp %>%
  stackApply(1:12, mean) %>%
  crop(bbox) %>%
  mask(na.mask)

streamplot(stack(u[[1]], v[[1]]), isField = 'dXY')
streamplot(stack(u[[7]], v[[7]]), isField = 'dXY')

u.lcc <- u %>% projectRaster(crs = "+proj=lcc")
v.lcc <- v %>% projectRaster(crs = "+proj=lcc")
dir <- (270 - atan2(v.lcc, u.lcc) * (180 / pi)) %% 360
#writeRaster(dir, 'dir.nc')
vel <- sqrt(u.lcc ^ 2 + v.lcc ^ 2)

delta <- abs(dir - aspect) # distance between wind angle and slope orientation
values(delta) <- ifelse(values(delta) > 180, 360 - values(delta), values(delta))
oro <- (sin(slope * 2 * pi / 180) * cos(delta * pi / 180) * vel * .5) %>% projectRaster(elev)
oro2 <- (sin(slope * 2 * pi / 180) * cos(delta * pi / 180)) %>% projectRaster(elev)

levelplot(oro, par.settings = RdBuTheme())
plot(slope)
plot(oro, prec.res)
levelplot(delta)
levelplot()
```


```{r}
dir.discrete <- dir %>% 
  reclassify(c(0, 45, 128, 45, 90, 1, 90, 135, 2, 135, 180, 4, 180, 225, 8, 225, 270, 16, 270, 315, 32, 315, 360, 64))

target.cells <- Which(elev, cells = T)
aco <- prec.obs
for(i in 1:12){
  aco[[i]][target.cells] <- mclapply(target.cells, function(x){
    dir.discrete[[i]] %>%
    flowPath(x) %>%
    xyFromCell(elev, .) %>%
    length
}) %>% unlist
}


levelplot(1/aco*precc)
```

```{r}
month <- prec.obs %>% setValues(c(as.factor(rep(1:12, each = ncell(elev)))))
lat <- elev %>%
     coordinates %>%
     .[,2] %>% 
     setValues(elev, .)

lon <- elev %>%
     coordinates %>%
     .[,1] %>% 
     setValues(elev, .)

precl <- brick('~/Downloads/b40.lm1850-2005.1deg.002.cam2.h0.PRECL.185001-200512.nc') %>% 
  .[[1212:1871]] %>%
  `*`(2629743830) %>%
  rotate %>%
  crop(bbox) %>%
  tpsInterp %>%
  stackApply(1:12, mean) %>%
  crop(bbox) %>%
  mask(na.mask)

precc <- brick('~/Downloads/b40.lm1850-2005.1deg.002.cam2.h0.PRECC.185001-200512.nc') %>% 
  .[[1212:1871]] %>%
  `*`(2629743830) %>%
  rotate %>%
  crop(bbox) %>%
  tpsInterp %>%
  stackApply(1:12, mean) %>%
  crop(bbox) %>%
  mask(na.mask)
precc[precc[] <= 0] <- 0.001
precl[precl[] <= 0] <- 0.001

levelplot(brick(c(sum(prec.obs), sum(precl) + sum(precc), sum(prec.obs) - (sum(precl) + sum(precc)))))
```

```{r}
prec.res <- prec.obs - (precl + precc)

levelplot(prec.res, par.settings = RdBuTheme(), at = seq(-150,150,20))
res <- sum(prec.res)
plot(dco, prec.res)
plot(dco, mean(prec.res))
plot(oro, prec.res)
plot(dir, prec.res)
plot(dir, vel)
```

```{r}
aco <- oro
vars <- sapply(1:12, function(x){
  brick(prec.obs[[x]], precc[[x]], precl[[x]], dir[[x]] %>% projectRaster(elev), 
        vel[[x]] %>% projectRaster(elev), delta[[x]] %>% projectRaster(elev), oro[[x]], oro2[[x]], aco[[x]], dco, rough, elev, lat, lon, month[[x]]) %>%
    setNames(c('prec.obs', 'precc', 'precl', 'dir', 'vel', 'delta', 'oro', 'oro2', 'aco', 'dco', 'rough', 'elev', 'lat', 'lon', 'month'))
})

prec.dat <- lapply(vars, as.data.frame, na.rm = T) %>% 
  do.call(rbind, .) %>%
  filter(prec.obs > 0)
```

```{r}
prec.mod <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'))
prec.mod1 <- bam(prec.obs ~ s(precc, bs = 'cr', k = 10) +
                  s(precl, bs = 'cr', k = 10),
                data = prec.dat, family = Gamma(link = 'log'))
prec.mod2 <- bam(prec.obs ~ s(log(precc), bs = 'cr', k = 10) +
                  s(log(precl), bs = 'cr', k = 10),
                data = prec.dat, family = Gamma(link = 'log'))
```
Varying coefficient with elevation seasonally
```{r}
ggplot(prec.dat, aes(elev, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

```{r}
ggplot(prec.dat, aes(rough*(1/dco), prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```


direction and season interaction
```{r}
ggplot(prec.dat, aes(dir, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

```{r}
ggplot(prec.dat, aes(dco, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

interaction doesn't vary seasonally
```{r}
ggplot(prec.dat, aes(dco*dir, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

```{r}
ggplot(prec.dat, aes(oro, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

```{r}
ggplot(prec.dat, aes(oro*dco, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(delta, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(vel, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(oro2, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```

```{r}
ggplot(prec.dat, aes(lat, prec.obs)) +
  geom_point(aes(color = elev), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(lon, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(precl, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(precc, prec.obs)) +
  geom_point(aes(color = as.factor(month)), alpha = .1, size = .3) +
  geom_smooth() +
  facet_wrap(~as.factor(month)) +
  theme_minimal()
```
```{r}
ggplot(prec.dat, aes(as.factor(month))) +
  geom_bar(aes(weight = prec.obs, fill = ..count..)) +
  theme_minimal()
```
```{r}
prec.dat %>% 
  group_by(month) %>%
  transmute(prc = mean(prec.obs)) %>%
  ggplot(aes(month, prc))+
  geom_line()
```

```{r}
prec.mod3 <- gam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                   s(elev, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')
prec.mod4 <- gam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                   s(elev, bs = 'cr') +
                   s(oro, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')
prec.mod5 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                   s(elev, bs = 'cr') +
                   s(oro, bs = 'cr') +
                   ti(precl, oro),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod6 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                   s(elev, bs = 'cr') +
                   s(oro, k = 20, bs = 'cr') +
                   s(dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod7 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                   s(elev, bs = 'cr') +
                   s(oro, bs = 'cr') +
                   ti(precl, dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod8 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod9 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  te(aco, oro, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod10 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr') +
                    s(dco, bs = 'cr') +
                    s(oro, k = 20, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod11 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr') +
                  s(oro, k = 20, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod12 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                    s(dco, bs = 'cr') +
                    te(oro, aco),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod13 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr') +
                    s(dco, bs = 'cr') +
                    te(oro, precl),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod14 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr') +
                    s(dco, bs = 'cr') +
                    s(oro, k = 20, bs = 'cr') +
                    ti(precl, aco),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod15 <- bam(prec.obs ~ s(precc, bs = 'cr') +
                  s(precl, bs = 'cr') +
                  s(elev, bs = 'cr') +
                  s(aco, bs = 'cr') +
                    te(oro, precl),
                data = prec.dat, family = Gamma(link = 'log'), select = T, method = 'REML')
prec.mod16 <- bam(prec.obs ~ s(precl, bs = 'cr') +
                    s(precc, bs = 'cr') +
                    s(elev, bs = 'cr') +
                    te(dco, dir, bs = c('cr', 'cc')),
                  data = prec.dat, family = Gamma(link = 'log'))
prec.mod17 <- bam(prec.obs ~ s(precl, bs = 'cr') +
                    s(precc, bs = 'cr') +
                    s(elev, bs = 'cr') +
                    te(dco, oro, k = c(5, 30)),
                  data = prec.dat, family = Gamma(link = 'log'))

prec.mod19 <- bam(prec.obs ~ s(precc, bs = 'cr',k = 30) +
                  s(precl, bs = 'cr', k = 10) +
                   s(elev, bs = 'cr') +
                   te(dco, dir, bs = c('cr', 'cc')),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')

prec.mod20 <- bam(prec.obs ~ s(precc, bs = 'cr',k = 30) +
                  s(precl, bs = 'cr', k = 10) +
                   s(elev, bs = 'cr') +
                    s(oro, bs = 'cr', k = 30) +
                   te(dco, dir, bs = c('cr', 'cc')),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')

prec.mod21 <- bam(prec.obs ~ te(precc, month, bs = c('cr', 'cc')) +
                  s(precl, bs = 'cr', k = 10) +
                   s(elev, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')

prec.mod22 <- bam(prec.obs ~ te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                  s(precl, bs = 'cr', k = 10) +
                   s(elev, bs = 'cr') +
                  te(dco, dir, bs = c('cr', 'cc')),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')
prec.mod23 <- bam(prec.obs ~ te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                  s(precl, bs = 'cr', k = 10) +
                   s(elev, bs = 'cr') +
                    s(oro, bs = 'cr', k = 30) +
                  te(dco, dir, bs = c('cr', 'cc')),
                data = prec.dat, family = Gamma(link = 'log'), method = 'REML')


knots <- list(month = c(0.5, seq(1, 12, length = 10), 12.5))

prec.mod24 <- bam(prec.obs ~ s(month, bs = 'cc', k = 12) +
                    s(precc, bs = 'cr', k = 10) +
                    s(precl, bs = 'cr', k = 10) +
                    ti(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

prec.mod25 <- bam(prec.obs ~ 
                    s(precl, bs = 'cr', k = 10) +
                    te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

prec.mod26 <- bam(prec.obs ~ 
                    s(precl, bs = 'cr', k = 10) +
                    te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr') +
                    te(rough, dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

prec.mod27 <- bam(prec.obs ~ s(precl, bs = 'cr', k = 10) +
                    te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr') +
                    s(oro, bs = 'cr', k = 30) +
                    te(rough, dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

prec.mod28 <- bam(prec.obs ~ s(precl, bs = 'cr', k = 10) +
                    te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr') +
                    s(oro, bs = 'cr', k = 30) +
                    s(vel, bs = 'cr', k = 10) +
                    te(rough, dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)
prec.mod29 <- bam(prec.obs ~ s(precl, bs = 'cr', k = 10) +
                    te(precc, month, bs = c('cr', 'cc'), k = c(10, 12)) +
                   s(elev, bs = 'cr') +
                    s(oro, bs = 'cr', k = 30) +
                    te(vel, delta) +
                    te(rough, dco, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

prec.mod30 <- bam(prec.obs ~ 
                    s(precl, bs = 'cr', k = 10) +
                    s(precc, as.factor(month), bs = 'fs') +
                   s(elev, bs = 'cr'),
                data = prec.dat, family = Gamma(link = 'log'), knots = knots, method = 'REML', select = T)

plot(prec.mod25, pers = T)
summary(prec.mod24)

prec.mod22$residuals^2 %>% mean %>% sqrt

prec.mod$aic;prec.mod1$aic;prec.mod2$aic;prec.mod3$aic;prec.mod4$aic;prec.mod5$aic;prec.mod6$aic;prec.mod7$aic;prec.mod8$aic;prec.mod9$aic;prec.mod10$aic;prec.mod11$aic;prec.mod12$aic;prec.mod13$aic;prec.mod14$aic;prec.mod15$aic;prec.mod16$aic;prec.mod17$aic;prec.mod19$aic;prec.mod20$aic;prec.mod21$aic;prec.mod22$aic;prec.mod23$aic;prec.mod24$aic;prec.mod25$aic;prec.mod26$aic;prec.mod27$aic;prec.mod28$aic;prec.mod29$aic;prec.mod30$aic



preds <- lapply(vars, predict, prec.mod27, type = 'response') %>% brick
levelplot(prec.obs - preds, at = seq(-100, 100, 20), par.settings = BuRdTheme())
levelplot((sum(prec.obs) - sum(preds))/sum(prec.obs), at = seq(-100, 100, 10), par.settings = BuRdTheme())
levelplot((sum(prec.obs) - sum(preds)), at = seq(-200, 200, 20), par.settings = BuRdTheme())

levelplot(brick(sum(prec.obs), sum(preds)))
levelplot(preds)
levelplot(precc + precl)
levelplot(brick(precc[[7]], prec.obs[[7]]))
```

Use geosphere to calculate air paths
```{r}

```

```{r}

```

