---
title: "Modern Climate"
author: "Nick Gauthier"
date: "6/7/2017"
output: 
  html_document: 
    highlight: pygments
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Present Day Climate in North Africa
```{r}
library(raster)
library(rasterVis)
library(tidyverse)
library(ClimClass)
```


```{r}
bbox <- extent(-10, 20, 28, 38)
+proj=aea +lat_1=31.333333333333332 +lat_2=36.666666666666664 +lon_0=5

prec <- getData('worldclim', var = 'prec', res = 2.5) %>%
  crop(bbox)

na.clump <- clump(prec[[1]])
prec <- mask(prec, na.clump, maskvalue = 7, inverse = T)

tmin <- getData('worldclim', var = 'tmin', res = 2.5) %>%
  crop(bbox) %>%
  mask(na.clump, maskvalue = 7, inverse = T) %>%
  `/`(10)

tmax <- getData('worldclim', var = 'tmax', res = 2.5) %>%
  crop(bbox) %>%
  mask(na.clump, maskvalue = 7, inverse = T) %>%
  `/`(10)
```

```{r cache = T }
koeppen_map <- function(x){
  ifelse(is.na(prec[x][1]), 
         return(NA),
      return(data_frame(month = 1:12,
           P = c(prec[x]),
           Tx = c(tmax[x]),
           Tn = c(tmin[x])) %>%
    mutate(Tm = (Tx + Tn) / 2) %>%
    koeppen_geiger(clim.resume_verbose = F) %>%
    .$class %>%
      as.character))
}


clim_class1 <- mclapply(1:ncell(prec), koeppen_map, mc.cores = detectCores()) %>% 
  unlist %>%
  as.factor %>%
  setValues(prec[[1]], .)
```


```{r}
clim_class1 %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  mutate(class = recode_factor(prec1_VALUE, BSh = 'Hot semi-arid',
  BSk = 'Cold semi-arid',
  BWh = 'Hot desert',
  BWk = 'Cold desrt',
  Csa = 'Hot-summer Mediterranean',
  Csb = 'Warm-summer Mediterranean',
  Dsb = 'Warm, dry-summer continental',
  Dsc = 'Dry-summer subarctic')) %>%
  ggplot(aes(x, y, fill = class)) +
  geom_raster() +
  labs(title = 'Present day climate of North Africa', subtitle = 'Based on WorldClim data') +
  scale_fill_discrete(name = 'Köppen-Geiger classification') +
  theme_void() +
  coord_quickmap()
```
Now try again with chirps and modis data.
  
```{r}
mod_chirps <- list.files('~/gdrive/Data/MOD11C3v6.0-CHIRPSv2.0_MONTHLY_03m/', full.names = T) %>%
  stack %>%
  crop(bbox)
mod_chirps[mod_chirps[] == -9999] <- NA
plot(mod_chirps[[1]])

prec <- mod_chirps[[1:12]]

tmax <- mod_chirps[[13:24]]

tmin <- mod_chirps[[37:48]]

clim_class2 <- mclapply(1:ncell(prec), koeppen_map, mc.cores = detectCores()) %>% 
  unlist %>%
  as.factor %>%
  setValues(prec[[1]], .)
clim_class2 %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  mutate(class = recode_factor(CHIRPSv2.0_Precip_Month_01_03m_VALUE, BSh = 'Hot semi-arid',
  BSk = 'Cold semi-arid',
  BWh = 'Hot desert',
  BWk = 'Cold desrt',
  Csa = 'Hot-summer Mediterranean',
  Csb = 'Warm-summer Mediterranean',
  Dsb = 'Warm, dry-summer continental',
  Dsc = 'Dry-summer subarctic')) %>%
  ggplot(aes(x, y, fill = class)) +
  geom_raster() +
  labs(title = 'Present day climate of North Africa', subtitle = 'Based on WorldClim data') +
  scale_fill_discrete(name = 'Köppen-Geiger classification') +
  theme_void() +
  coord_quickmap()
```


Growing degree days
```{r}
levelplot(tmax)
month.days <- c(15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349)

tmax.dat <- tmax %>% 
  raster::as.data.frame(xy = T, na.rm = T) %>%
  gather(month, value, 3:14) %>%
  mutate(doy = rep(month.days, each = 84103))

tmax.dat$cell <- cellFromXY(tmax, as.matrix(tmax.dat[,1:2])) %>% as.factor

tmax.dat <- getValues(tmax)
colnames(tmax.dat) <- month.abb

library(mgcv)
library(pbapply)

tmax.out <- pbapply(tmax.dat, 1, function(x){
    if(any(is.na(x))){return(rep(NA, 365))} else{
      dat <- data.frame(doy =  c(15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349),
                        tmax = x)
      mod <- gam(tmax ~ s(doy, bs = 'cc', k = 12), knots = list(doy = c(1, 366)), data = dat)
      return(predict.gam(mod, data.frame(doy = 1:365)))
    }
}) %>% t
tmax.out

tmax.daily <- tmax[[rep(1, 365)]] %>% brick %>% setValues(tmax.out)
levelplot(tmax.daily[[month.days]] - tmax)
tmin.dat <- getValues(tmin)
colnames(tmin.dat) <- month.abb
tmin.out <- pbapply(tmin.dat, 1, function(x){
    if(any(is.na(x))){return(rep(NA, 365))} else{
      dat <- data.frame(doy =  c(15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349),
                        tmin = x)
      mod <- gam(tmin ~ s(doy, bs = 'cc', k = 12), knots = list(doy = c(1, 366)), data = dat)
      return(predict.gam(mod, data.frame(doy = 1:365)))
    }
}) %>% t
tmin.daily <- tmin[[rep(1, 365)]] %>% brick %>% setValues(tmin.out)

tmean.daily <- (tmin.daily + tmax.daily) / 2
max(tmean.daily - 5, 0)

gdd <- tmean.daily %>% reclassify(c(-Inf, 5, 0)) %>% sum
levelplot(gdd)
gdd.index <- 1 / (1 + exp(0.0052 * (1334 - gdd)))
levelplot(gdd.index)
```
water demand
```{r}
library(SPEI)
lats <- tmin[[1]] %>% coordinates %>% .[,2] %>% setValues(tmin[[1]], .)
plot(lats)

hargreaves((tmin %>% getValues %>% t), (tmax %>% getValues %>% t), lat = rep(33, 120000), na.rm = T) %>%
  t %>%
  setValues(tmin, .) %>%
  levelplot

edit(hargreaves)
thornthwaite((((tmax + tmin) / 2) %>% getValues %>% t), lat = (lats %>% getValues), na.rm = T) %>%
  t %>%
  setValues(tmin, .) %>%
  levelplot

alpha <- raster('~/Downloads/ALPHA/alpha/') %>% projectRaster(tmin[[1]])/100
plot(alpha)
alpha.index <- 1 / (1 + exp(14.705 * (0.3295 - alpha)))
plot(alpha)
```
Soil Chemistry
```{r}
ph <- raster('~/Downloads/PHIHOX_M_sl4_250m_ll.tif') / 10
carbon <- raster('~/Downloads/ORCDRC_M_sl4_250m_ll.tif')
```


# Land Use

```{r}
avhrr_colors <- c('#444f89', '#016400', '#018200', '#97bf47', '#02dc00', '#00ff00', '#92ae2f',
                  '#dcce00', '#ffad00', '#fffbc3', '#8c4809', '#f7a5ff', '#ffc7ae', '#efefe8', '#00ffff')

avhrr <- raster('AVHRR_1km_LANDCOVER_1981_1994.GLOBAL.tif') %>%
  crop(bbox) %>%
  as.data.frame(xy = T) %>%
  mutate(class = recode_factor(AVHRR_1km_LANDCOVER_1981_1994.GLOBAL,
                               `0` = 'Water',
                               `1` = 'Evergreen Needleleaf forest',
                               `2` = 'Evergreen Broadleaf forest',
                               `3` = 'Deciduous Needleleaf forest',
                               `4` = 'Deciduous Broadleaf forest',
                               `5` = 'Mixed forest',
                               `6` = 'Woodland',
                               `7` = 'Wooded grassland',
                               `8` = 'Closed shrubland',
                               `9` = 'Open shrubland',
                               `10` = 'Grasslands',
                               `11` = 'Cropland',
                               `12` = 'Bare ground',
                               `13` = 'Permanent snow or ice',
                               `14` = 'Urban and built-up'))

ggplot(avhrr, aes(x, y, fill = class)) +
  geom_raster() +
  coord_quickmap() +
  scale_fill_manual(values = avhrr_colors) +
  theme_void()
```

