---
title: "Surface Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Creation of surface datasets for Roman LULCC simulations

## Setup
Import necessary packages

```{r}
library(tidyverse)
```

```{r}
#devtools::install_github("bergant/nlexperiment")
library(nlexperiment)
nl_netlogo_path('/home/nick/Netlogo/NetLogo 6.0.2/app/') 
```

```{r}
cities <- read.csv('data/NA_cities.csv') %>%
  mutate(population = 41.834 * Size ^ 1.3361) %>%
  select(Name, population) %>%
  filter(!is.na(population)) %>%
  mutate(pop_normalized = population / mean(population)) %>%
  select(-population)
```

```{r}
experiment <- nl_experiment( 
  model_file = '/home/nick/gdrive/Projects/North-Africa/cities-nw-calib.nlogo',
  while_condition = 'ticks < sim-length',
  param_values = nl_param_lhs(
    n = 500,
    sim_length = c(100, 500),
    coastal_flows = c(0, 1),
    alpha = c(0.85, 1.15),
    beta = c(20, 60)
  ),
  mapping = c(coastal_flows = 'coastal-flows', sim_length = 'sim-length'),
  agents_after = list(
    individuals = agent_set(
      vars = c('name', 'population'),
      agents = 'cities'
    )
  ),
  random_seed = 1
)  
```

```{r}
result <- nl_run(experiment, parallel = T, print_progress = T)
```



```{r}
results <- nl_get_result(result, type = 'agents_after', sub_type = 'individuals') %>%
  select(-run_id) %>%
  right_join(cities, by = c('name' = 'Name')) %>%
  mutate(abs.error = abs(population - pop_normalized)) %>%
  group_by(coastal_flows, sim_length, alpha, beta) %>%
  summarise(mae = mean(abs.error))
```


```{r}
ggplot(results, aes(mae)) + geom_density()

qplot(sim_length, mae, data = results, geom = 'point')
qplot(alpha, mae, data = results, geom = 'point')
qplot(beta, mae, data = results, geom = 'point')
qplot(coastal_flows, mae, data = results, geom = 'point')
```

Find the best performing runs
```{r}
summary(results$mae)
```

```{r}
results %>%
  filter(mae < 1.176) %>%
  ggplot(aes(alpha, beta, color = mae)) +
  geom_point()
```

sim length of about 150
```{r}
results %>%
  filter(mae < 1.176) %>%
  ggplot(aes(sim_length)) + geom_density()
results %>%
  filter(mae < 1.176) %>%
  ggplot(aes(coastal_flows)) + geom_density()
results %>%
  filter(mae < 1.176) %>%
  ggplot(aes(alpha)) + geom_density()
results %>%
  filter(mae < 1.176) %>%
  ggplot(aes(beta)) + geom_density()

filter(results, mae < 1.05)
```

Optimization
```{r}
library(dfoptim)

cl <- nl_eval_init(experiment, parallel = TRUE)
trace <- nl_eval_tracer(verbose = FALSE)
param_range <- nl_get_param_range(experiment)   
set.seed(1) 

o_result <- nmkb(
  par = (param_range$upper + param_range$lower)/2,
  fn = nl_eval_run, 
    experiment = experiment, 
    criteria = "eval_value", 
    call_back = trace$add, 
    parallel = TRUE, cluster = cl,
    param_names = names(param_range$lower),
  lower = param_range$lower, 
  upper = param_range$upper, 
  control = list(maxfeval = 200)
)

nl_eval_close(parallel = TRUE, cl)
```

