---
title: "Potential PFT"
output: html_notebook
---

```{r}
library(tidyverse)
library(raster)
library(mgcv)
library(RStoolbox)
```

# Prentice et al method
```{r}
temp <- brick('Data/CHELSA/temp.nc')
t_warm <- max(temp)
t_cold <- min(temp)
alpha <- raster('Data/CHELSA/alpha.nc')
gdd0 <- raster('gdd0_global.tif')
gdd5 <- raster('gdd5_global.tif')
```


```{r}
tropical.evergreen <- (t_cold > 15.5 & alpha > .8)
tropical.raingreen <- (t_cold > 15.5 & alpha > .45 & alpha < .95)
warm.temperate.evergreen <- (t_cold > 5 & alpha > .65)
temperate.summergreen <- (t_cold > -15 & t_cold < 15.5 & gdd5 > 1200 & alpha > .65)
cool.temperate.conifer <- (t_cold > -19 & t_cold < 5 & gdd5 > 900 & alpha > .65)
boreal.evergreen.conifer <- (t_cold > -35 & t_cold < -2 & gdd5 > 350 & alpha > .75)
boreal.summergreen <- (t_cold < 5 & gdd5 > 350 & alpha > .65)

succulent <- (t_cold > 5 & alpha > .28)
warm.grass.shrub <- (t_warm > 22 & alpha > .18)
cool.grass.shrub <- (gdd5 > 500 & alpha > .33)
cold.grass.shrub <- (gdd0 > 100 & alpha > .33)
hot.desert.shrub <- (t_warm > 22)
cold.desert.shrub <- (gdd0 > 100)
```





# BIOME6000

Multinomial logistic regression using BIOME 6000 data.

First import and processthe BIOME 6000 data.
```{r}
biomes <- readxl::read_excel('BIOME4-2.xls', sheet = 3) %>% 
  dplyr::select(Lon, Lat, biome = Biome00k, megabiome = MegaBiome00k) %>%
  filter(!is.na(biome)) %>%
  mutate(megabiome = if_else(megabiome == 'dry tundra', 'tundra', megabiome)) %>%
  mutate(biome = as.factor(biome), megabiome = as.factor(megabiome), megabiome.int = as.numeric(megabiome) - 1)

ggplot(biomes, aes(Lon, Lat)) +
  borders("world", colour="gray50", fill="gray50") +
  geom_point(aes(color = megabiome)) +
  coord_fixed() +
  theme_void()

ggplot(biomes, aes(x = megabiome, fill = megabiome)) +
  geom_bar()
```

```{r}
bioclim <- brick('Data/CHELSA/bioclim.nc')
clim.pca <- rasterPCA(bioclim, spca = T)
clim.pca
summary(clim.pca$model)

plot(clim.pca$model)
plot(clim.pca$map[[1:8]])
```

Now add soil and gdd/alpha parameters.
```{r}
beginCluster(2)

gdd <- raster('gdd_global.tif')
alpha <- raster('~/Downloads/CGIAR PET/ALPHA/alpha/w001001.adf') %>% resample(gdd)
names(alpha) <- 'alpha'
pet <- brick('Data/CHELSA/pet.nc') %>% sum
ph.sg <- raster('~/Downloads/SoilGrids250/PHIHOX_M_sl4_250m_ll.tif') %>%
  resample(gdd)
c.sg <- raster('~/Downloads/SoilGrids250/OCSTHA_M_30cm_250m_ll.tif') %>%
  resample(gdd)

endCluster()
```

```{r}
preds <- brick(c(clim.pca$map[[1:4]], gdd, alpha, pet, ph.sg, c.sg))
names(preds) <- c('PC1', 'PC2', 'PC3', 'PC4', 'gdd', 'alpha', 'pet', 'ph', 'carbon')

dat <- cbind(biomes, raster::extract(preds, biomes[,1:2], na.rm = T))
```

Lets fit a series of one-to-many logistic regresstions with select=TRUE to select candidate models for each megabiome.
```{r}
library(parallel)
cl <- makeCluster(2)


```


Confirming that the 4 pcas are the best, if we add 4 more pcas, they are penalized to 0.
```{r}
boreal.mod.pca <- mutate(dat, binary = if_else(megabiome.int == 0, 1, 0)) %>%
  gam(binary ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'), data = ., method = 'REML', select = T, family = binomial, cluster = cl)
plot(boreal.mod.pca)

summary(boreal.mod.pca)
gam.check(boreal.mod.pca)
boreal.mod.pca$aic
boreal.mod$aic


boreal.mod.pca2 <- mutate(dat, binary = if_else(megabiome.int == 0, 1, 0)) %>%
  gam(binary ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(PC5, bs = 'cr') + s(PC6, bs = 'cr') + s(PC7, bs = 'cr') + s(PC8, bs = 'cr'), data = ., method = 'REML', select = T, family = binomial, cluster = cl)

plot(boreal.mod.pca2)
summary(boreal.mod.pca2)
boreal.mod.pca2$aic
```

```{r}
boreal.mod <- mutate(dat, binary = if_else(megabiome.int == 0, 1, 0)) %>%
  gam(binary ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr')
      + s(gdd, bs = 'cr') + s(alpha, bs = 'cr') + s(pet, bs = 'cr') + s(ph, bs = 'cr') + s(carbon, bs = 'cr'), data = ., method = 'REML', select = T, family = binomial, cluster = cl)
plot(boreal.mod)
```


```{r}
mod1 <- gam(list(megabiome.int 
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr')), family = multinom(K = 8), method = 'REML', select = T, data = dat, optimizer = 'perf')


gam.check(mod1)
summary(mod1)
mod1$aic
plot(mod1, scale = -1)
saveRDS(mod1, 'mod1')

predict(mod1, dat, type = 'response')
predictions <- predict(preds, mod1, type = 'response', index = 1:9)
names(predictions) <- biomes$megabiome %>% levels
rasterVis::levelplot(predictions)
```

```{r}
mod3 <- gam(list(biome.int ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr') + s(Lon, Lat, bs = 'sos', k = 100)), family = multinom(K = 8), method = 'REML', control = list(nthreads = 4), optimizer = 'perf', data = dat2)

mod3$aic
plot(mod3, scale = 0)
summary(mod3)
```
```{r}
mod4 <- gam(list(biome.int ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr'),
                 ~ s(PC1, bs = 'cr') + s(PC2, bs = 'cr') + s(PC3, bs = 'cr') + s(PC4, bs = 'cr')), family = multinom(K = 8), method = 'REML', control = list(nthreads = 4), optimizer = 'perf', data = dat2)
gam.check(mod3)
summary(mod3)
```

```{r}
mod2 <- gam(list(biome.int 
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr'),
                 ~ s(bio1, bs = 'cr') + s(bio2, bs = 'cr') + s(bio3, bs = 'cr') + s(bio4, bs = 'cr') + s(bio5, bs = 'cr') + s(bio6, bs = 'cr') + s(bio7, bs = 'cr') + s(bio8, bs = 'cr') + s(bio9, bs = 'cr') + s(bio10, bs = 'cr') + s(bio11, bs = 'cr') + s(bio12, bs = 'cr') + s(bio13, bs = 'cr') + s(bio14, bs = 'cr') + s(bio15, bs = 'cr') + s(bio16, bs = 'cr') + s(bio17, bs = 'cr') + s(bio18, bs = 'cr') + s(bio19, bs = 'cr')), 
            family = multinom(K = 8), data = dat, select = T)
```

```{r}
srtm <- raster('~/gdrive/Data/SRTM_1km.tif')

elev <- srtm %>% aggregate(pft)
```

# PFT
```{r}
library(ncdf4)
pft <- nc_open('~/Downloads/mksrf_pft_potv.nc') #%>% ncvar_get(varid = 'PCT_PFT')
pft
test <- pft %>% brick(xmn = -180, xmx = 180, ymn = -90, ymx = 90, transpose = F)
rasterVis::levelplot(test[[1]])
lat <- ncvar_get(pft, varid = 'LAT')
lon <- ncvar_get(pft, varid = 'LON')
nc_close(pft)
vals <- brick('~/Downloads/mksrf_pft_potv.nc') %>% getValues
landmask <- raster('~/Downloads/mksrf_pft_potv.nc', varname = 'LANDMASK') 
plot(landmask)
landmask <- landmask %>% getValues %>% setValues(temp[[1]], .)
landmask[landmask == 0] <- NA
crs(landmask) <- "+proj=longlat +datum=WGS84"
#Generate coordinates for each grid cell
 x<- rep(lon, length(lat))
 y<- rep(lat, each = length(lon))
 sp<- SpatialPoints(cbind(x,y))
temp<- SpatialPixels(points = sp) %>% raster %>% brick(rep(., 12))
test <- setValues(temp, vals) %>% mask(landmask)
crs(test) <- "+proj=longlat +datum=WGS84" 

rasterVis::levelplot(test)

pft
plot(pft[[1]])
```