---
title: "Mapping Roman North Africa"
author: "Nick"
date: "6/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(raster)
library(rgdal)
library(rasterVis)
library(viridis)
library(tidyverse)
library(stringr)
library(pleiades)
```

Import SRTM basemap
```{r}
bbox <- extent(-10, 20, 28, 38)
srtm <- raster('Data/SRTM_NE_250m_TIF/SRTM_NE_250m.tif') %>%
  crop(bbox)

slope <- terrain(srtm, unit = 'degrees')

plot(srtm)
```


```{r}
cities <- read.csv('NA_cities.csv') %>%
  group_by(BA_rank) %>% 
  mutate(size_est = ifelse(is.na(Size), mean(Size, na.rm=TRUE), Size)) %>%
  mutate(population = 1.7 * Size^.635, pop_est = 1.7 * size_est^.635)

roads <- readOGR('Data/Shapefiles/ba_roads.shp') %>%
  spTransform(CRS('+proj=longlat')) %>%
  crop(bbox) %>%
  fortify

aqueducts <- readOGR('Data/Shapefiles/aqueducts.shp') %>%
  spTransform(CRS('+proj=longlat')) %>%
  crop(bbox)
```

```{r}
ggplot(cities, aes(lon, lat)) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5) +
  geom_point(aes(color = pop_est, size = pop_est), alpha = .8) +
  scale_size_area() +
  scale_color_viridis() +
  theme_void() +
  coord_fixed()
```

```{r}
with(cities, cities[rep(1:nrow(cities), pop_est),]) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()
```


  
```{r}
places <- pl_search_places() %>%
  filter(locationPrecision == 'precise') %>%
  select(title, type = featureTypes, description, 
         lon = reprLong, lat = reprLat, 
         periods = timePeriods, minDate, maxDate, id, tags) %>%
  filter(between(lat, 28, 38) & between(lon, -10, 20)) %>%
  collect  %>%
  filter(str_detect(periods, 'R')) %>%
  print

places %>% filter(str_detect(type, 'villa')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()

places %>% filter(str_detect(type, 'settlement')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()

places %>% filter(str_detect(type, 'mine')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()

places %>% filter(str_detect(type, 'spring')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()

places %>% filter(str_detect(type, 'oasis')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void()


places %>% filter(str_detect(type, 'settlement')) %>%
ggplot(aes(lon, lat)) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = F, n = 500, h = 1) +
  geom_path(data = roads, aes(long, lat, group = group), alpha = .5, color = 'white') +
  scale_fill_viridis() +
  coord_fixed() +
  theme_void() +
  geom_point(data = cities, aes(lon, lat, size = pop_est), color = 'white') +
  scale_size_area()


major <- settlements %>% filter(str_detect(tags, 'major=1'))
```




```{r transition}
library(gdistance)

altDiff <- function(x){x[2] - x[1]}
hd <- transition(srtm, altDiff, 8, symm=FALSE)
adj <- adjacent(srtm, cells=1:ncell(srtm), pairs=TRUE, directions=8)
```

Create conductance matrix with geocorrection for lcps
```{r lcp_conductance}
slope.c <- geoCorrection(hd, type = 'c')
speed.c <- slope.c
speed.c[adj] <- 6 * exp(-3.5 * abs(slope.c[adj] + 0.05))
Conductance.c <- geoCorrection(speed.c, type = 'c')
rm(slope.c, speed.c)
```

```{r}
sites <- major %>%
  select(lon, lat) %>%
  as.matrix

acc <- accCost(Conductance.c, sites) %>%
  mask(srtm)

plot(acc/3600<3)
```


Create conductance matrix with geocorrection for random walks
```{r randomwalk_conductance}
slope.r <- geoCorrection(hd, type = 'r', scl =T)
speed.r <- slope.r
speed.r[adj] <- 6 * exp(-3.5 * abs(slope.r[adj] + 0.05))
Conductance.r <- geoCorrection(speed.r, type = 'r', scl = T)
rm(slope.r, speed.r, hd, adj)
```


```{r}
pas <- passage(Conductance.r, sites, sites, theta = 1)
plot(pas)
```

```{r}
plot(c(cost_matrix), c(commute_matrix))
```



