---
title: "Mapping North Africa"
author: "Nick Gauthier"
date: "June 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r}
library(tidyverse)
library(raster)
```



## Elevation Data
Get country boundaries for spain, portugal, and italy to mask out from elevation
```{r}
euro.mask <- rbind(getData('GADM', country = 'PRT', level = 0),
                   getData('GADM', country = 'ESP', level = 0),
                   getData('GADM', country = 'ITA', level = 0))
```

First download and mosaic 90m srtm tiles over the study area.
```{r}

getData('SRTM', lon = -8, lat = 35)
getData('SRTM', lon = -3, lat = 35)
getData('SRTM', lon = 2, lat = 35)
getData('SRTM', lon = 7, lat = 35)
getData('SRTM', lon = 12, lat = 35)
getData('SRTM', lon = -8, lat = 40)
getData('SRTM', lon = -3, lat = 40)
getData('SRTM', lon = 2, lat = 40)
getData('SRTM', lon = 7, lat = 40)
getData('SRTM', lon = 12, lat = 40)



srtm <- list.files(pattern = '*.tif', recursive = T) %>% 
  lapply(raster) %>% 
  do.call(merge, .) %>%
  mask(euro.mask, inverse = T)

writeRaster(srtm, 'srtm_na.tif')
srtm <- raster('srtm_na.tif')
```

```{r}
plot(srtm)
```

```{r}
slope <- terrain(srtm, opt = 'slope', filename = 'slope.tif', overwrite = T)
aspect <- terrain(srtm, opt = 'aspect', filename = 'aspect.tif', overwrite = T)
TPI <- terrain(srtm, opt = 'TPI', filename = 'TPI.tif', overwrite = T)
TRI <- terrain(srtm, opt = 'TRI', filename  = 'TRI.tif', overwrite = T)
roughness <- terrain(srtm, opt = 'roughness', filename = 'roughness.tif', overwrite = T)
flowdir <- terrain(srtm, opt = 'flowdir', filename = 'flowdir.tif', overwrite = T)
```

```{r}
plot(slope)
plot(aspect)
plot(TPI)
plot(TRI)
plot(roughness)
plot(flowdir)
```


